# Generated by Django 3.2.6 on 2021-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_dailymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='objects',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='objektet',
            field=models.ManyToManyField(related_name='objektet', to='food.FoodMenu'),
        ),
    ]
