# Generated by Django 3.2.6 on 2021-08-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210818_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyMenu',
        ),
    ]
