# Generated by Django 3.2.6 on 2021-08-23 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_dailyfood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfood',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
